myData = [
 {
   "painting_index": 1,
   "title": "Nihonbashi: Clearing after Snow (日本橋雪晴, *Nihonbashi yukibare*)",
   "depicted": "Nihonbashi, Edo Castle, Mount Fuji",
   "remarks": "—",
   "date_of_painting": "1856-05",
   "latitude": 35.684028,
   "longitude": 139.77444,
   "imagethumb": "6/69/100_views_edo_001.jpg",
   "image": "6/69/100_views_edo_001.jpg/120px-100_views_edo_001.jpg"
 },
 {
   "painting_index": 2,
   "title": "Kasumigaseki (霞がせき)",
   "depicted": "Street (today Kasumigaseki-zaka), guardhouse of residence of Asano, barracks of samurai of the Kuroda clan, Edo Bay",
   "remarks": "Kadomatsu gate pines and manzai dancers indicate a setting around New Year; kite with Japanese character for fish (Jap. \"sakana\") is a reference to the publisher of the series, Sakanaya Eikichi",
   "date_of_painting": "1857-01",
   "latitude": 35.675667,
   "longitude": 139.748972,
   "imagethumb": "6/65/100_views_edo_002.jpg",
   "image": "6/65/100_views_edo_002.jpg/120px-100_views_edo_002.jpg"
 },
 {
   "painting_index": 3,
   "title": "Hibiya and Soto-Sakurada from Yamashita-chō (山下町日比谷外さくら田, *Yamashita-chō Hibiya Soto-Sakurada*)",
   "depicted": "Residence of *daimyō* Nabeshima Kansō from the Saga Domain, outer moat of Edo Castle, Mount Fuji",
   "remarks": "Kadomatsu pine, hagoita and kites indicate a setting around New year",
   "date_of_painting": "1857-12",
   "latitude": 35.67222,
   "longitude": 139.761028,
   "imagethumb": "5/55/100_views_edo_003.jpg",
   "image": "5/55/100_views_edo_003.jpg/120px-100_views_edo_003.jpg"
 },
 {
   "painting_index": 4,
   "title": "Tsukudajima and Eitai Bridge (永代橋佃しま, *Eitaibashi Tsukudajima*)",
   "depicted": "Eitai Bridge, Sumida River, fishing boats of Tsukudajima",
   "remarks": "An almost identical composition titled *Eitaibashi* by Hiroshige exists in the second volume of his \"Illustrated Souvenirs of Edo\"",
   "date_of_painting": "1857-02",
   "latitude": 35.677611,
   "longitude": 139.787417,
   "imagethumb": "1/19/100_views_edo_004.jpg",
   "image": "1/19/100_views_edo_004.jpg/120px-100_views_edo_004.jpg"
 },
 {
   "painting_index": 5,
   "title": "Ekōin Temple in Ryōgoku and Moto-Yanagi Bridge (両ごく回向院元柳橋, *Ryōgoku Ekōin Moto-Yanagibashi*)",
   "depicted": "Drum tower of Ekō-in, Honjo neighbourhood, Sumida River, residence of Matsudaira feudal lor of Tanba, Mount Fuji",
   "remarks": "Drum tower was associated with sumo tournaments held at Ekō-in; for marketing purposes the print appeared two months after a popular major exhibition of temple treasures at Ekō-in",
   "date_of_painting": "1857-05",
   "latitude": 35.69333,
   "longitude": 139.79194,
   "imagethumb": "9/99/100_views_edo_005.jpg",
   "image": "9/99/100_views_edo_005.jpg/120px-100_views_edo_005.jpg"
 },
 {
   "painting_index": 6,
   "title": "Hatsune Riding Ground in Bakuro-chō (馬喰町初音の馬場, *Bakuro-chō Hatsune no baba*)",
   "depicted": "Hatsune Riding Ground and district's fire watch tower",
   "remarks": "Dyers of Konya-chō district using riding grounds to dry their cloths",
   "date_of_painting": "1857-09",
   "latitude": 35.694611,
   "longitude": 139.783139,
   "imagethumb": "a/a0/100_views_edo_006.jpg",
   "image": "a/a0/100_views_edo_006.jpg/120px-100_views_edo_006.jpg"
 },
 {
   "painting_index": 7,
   "title": "Shops with Cotton Goods in Ōdenma-chō (大てんま町木綿店, *Ōtenma-chō momendana*)",
   "depicted": "Street scene with geishas, cotton shops in Ōdenma-chō",
   "remarks": "—",
   "date_of_painting": "1858-04",
   "latitude": 35.688528,
   "longitude": 139.776361,
   "imagethumb": "0/0b/100_views_edo_007.jpg",
   "image": "0/0b/100_views_edo_007.jpg/120px-100_views_edo_007.jpg"
 },
 {
   "painting_index": 8,
   "title": "Suruga-chō (する賀てふ, *Suruga tefu*)",
   "depicted": "Mitsui (yagō: Echigoya) textile stores, Mount Fuji",
   "remarks": "Echigoya later became the Mitsukoshi department store chain whose modern day headquarters are located on the left side of the street in the print",
   "date_of_painting": "1856-09",
   "latitude": 35.68625,
   "longitude": 139.773944,
   "imagethumb": "d/d0/100_views_edo_008.jpg",
   "image": "d/d0/100_views_edo_008.jpg/120px-100_views_edo_008.jpg"
 },
 {
   "painting_index": 9,
   "title": "Yatsukōji, Inside Sujikai Gate (筋違内八ツ小路, *Sujikai uchi Yatsukōji*)",
   "depicted": "Yatsukōji junction, Kanda River, Kanda Shrine",
   "remarks": "One of the few open spaces in Edo, created as fire-breaks",
   "date_of_painting": "1857-11",
   "latitude": 35.697361,
   "longitude": 139.769222,
   "imagethumb": "f/f0/100_views_edo_009.jpg",
   "image": "f/f0/100_views_edo_009.jpg/120px-100_views_edo_009.jpg"
 },
 {
   "painting_index": 10,
   "title": "Sunrise at Kanda Myōjin Shrine (神田明神曙之景, *Kanda Myōjin akebono no kei*)",
   "depicted": "Kanda Shrine",
   "remarks": "Probably produced as a souvenir of the shrine festival in memory of the Battle of Sekigahara celebrated on the 15th day of the 9th month",
   "date_of_painting": "1857-09",
   "latitude": 35.70194,
   "longitude": 139.767917,
   "imagethumb": "e/e5/100_views_edo_010.jpg",
   "image": "e/e5/100_views_edo_010.jpg/120px-100_views_edo_010.jpg"
 },
 {
   "painting_index": 11,
   "title": "Kiyomizu Hall and Shinobazu Pond at Ueno (上野清水堂不忍ノ池, *Ueno Kiyomizu-dō Shinobazu no ike*)",
   "depicted": "Kiyomizu Hall of Kan'ei-ji, Moon Pine, Shinobazu Pond",
   "remarks": "Depicted pines are in reality much smaller",
   "date_of_painting": "1856-04",
   "latitude": 35.712611,
   "longitude": 139.773556,
   "imagethumb": "1/1e/100_views_edo_011.jpg",
   "image": "1/1e/100_views_edo_011.jpg/120px-100_views_edo_011.jpg"
 },
 {
   "painting_index": 12,
   "title": "Ueno Yamashita (上野山した)",
   "depicted": "Iseya restaurant, temples",
   "remarks": "Published in the month after Hiroshige's death; composition probably based on his sketches but probably completed by Hiroshige II",
   "date_of_painting": "1858-10",
   "latitude": 35.71056,
   "longitude": 139.773472,
   "imagethumb": "7/72/100_views_edo_012.jpg",
   "image": "7/72/100_views_edo_012.jpg/120px-100_views_edo_012.jpg"
 },
 {
   "painting_index": 13,
   "title": "Shitaya Hirokōji (下谷広小路)",
   "depicted": "Hirokōji (\"Broadway\"), premises of textile retailer Matsuzakaya",
   "remarks": "Published in the same month in which the depicted Matsuzakaya store re-opened after the 1855 earthquake",
   "date_of_painting": "1856-09",
   "latitude": 35.707056,
   "longitude": 139.772694,
   "imagethumb": "6/68/100_views_edo_013.jpg",
   "image": "6/68/100_views_edo_013.jpg/120px-100_views_edo_013.jpg"
 },
 {
   "painting_index": 14,
   "title": "Temple Gardens in Nippori (日暮里寺院の林泉, *Nippori jiin no rinsen*)",
   "depicted": "Temple Gardens",
   "remarks": "Depicts cherries and azaleas in bloom while in reality they bloom at different times of the year",
   "date_of_painting": "1857-02",
   "latitude": 35.731056,
   "longitude": 139.766028,
   "imagethumb": "3/34/100_views_edo_014.jpg",
   "image": "3/34/100_views_edo_014.jpg/120px-100_views_edo_014.jpg"
 },
 {
   "painting_index": 15,
   "title": "Suwa Bluff in Nippori (日暮里諏訪の台, *Nippori Suwanodai*)",
   "depicted": "Suwa Myōjin Shrine grounds, Mount Tsukuba",
   "remarks": "—",
   "date_of_painting": "1856-05",
   "latitude": 35.730861,
   "longitude": 139.767083,
   "imagethumb": "9/93/100_views_edo_015.jpg",
   "image": "9/93/100_views_edo_015.jpg/120px-100_views_edo_015.jpg"
 },
 {
   "painting_index": 16,
   "title": "Flower Park and Dangozaka Slope in Sendagi (千駄木団子坂花屋敷, *Sendagi Dangozaka Hanayashiki*)",
   "depicted": "Cherry orchard, Pavilion of the Violet Spring (Shisentei)",
   "remarks": "The print is a reference to the reconstruction of the Shisentai after the 1855 earthquake and to Tokugawa Iesada's visit to the park two months prior to publication",
   "date_of_painting": "1856-05",
   "latitude": 35.725139,
   "longitude": 139.761222,
   "imagethumb": "5/57/100_views_edo_016.jpg",
   "image": "5/57/100_views_edo_016.jpg/120px-100_views_edo_016.jpg"
 },
 {
   "painting_index": 17,
   "title": "View to the North from Asukayama (飛鳥山北の眺望, *Asukayama kita no chōbō*)",
   "depicted": "Asukayama Park, Mount Tsukuba",
   "remarks": "Possibly inspired by Tokugawa Iesada's visit to the park two months prior to publication",
   "date_of_painting": "1856-05",
   "latitude": 35.75139,
   "longitude": 139.73833,
   "imagethumb": "f/fd/100_views_edo_017.jpg",
   "image": "f/fd/100_views_edo_017.jpg/120px-100_views_edo_017.jpg"
 },
 {
   "painting_index": 18,
   "title": "The Ōji Inari Shrine (王子稲荷の社, *Ōji Inari no yashiro*)",
   "depicted": "Ōji Inari Shrine, Mount Tsukuba",
   "remarks": "—",
   "date_of_painting": "1857-09",
   "latitude": 35.756083,
   "longitude": 139.73333,
   "imagethumb": "f/f3/100_views_edo_018.jpg",
   "image": "f/f3/100_views_edo_018.jpg/120px-100_views_edo_018.jpg"
 },
 {
   "painting_index": 19,
   "title": "Dam on the Otonashi River at Ōji, known as \"The Great Waterfall\" (王子音無川堰棣 世俗大瀧ト唱, *Ōji Otonashigawa entei, sezoku Ōtaki to tonau*)",
   "depicted": "Otonashi River, Amida Hall of Kinrin-ji temple, Takata-chō",
   "remarks": "Likely created to mark Tokugawa Iesada's visit to Kinrin-ji (Ōji Shrine) and Takata on the 21st day of the first month (also see no. 115, 116)",
   "date_of_painting": "1857-02",
   "latitude": 35.75222,
   "longitude": 139.73575,
   "imagethumb": "a/a0/100_views_edo_019.jpg",
   "image": "a/a0/100_views_edo_019.jpg/120px-100_views_edo_019.jpg"
 },
 {
   "painting_index": 20,
   "title": "The Kawaguchi Ferry and Zenkōji temple (川口のわたし善光寺, *Kawaguchi no watashi Zenkōji*)",
   "depicted": "Arakawa River, Zenkō-ji temple",
   "remarks": "A year after Hiroshige designed the print, the Buddha in the Amida Hall at the top was due to be exhibited publicly for the first time in 13 years; in a pun Hiroshige covered the hall of this \"secret Buddha\" with the title cartouche",
   "date_of_painting": "1857-02",
   "latitude": 35.79389,
   "longitude": 139.721306,
   "imagethumb": "5/59/100_views_edo_020.jpg",
   "image": "5/59/100_views_edo_020.jpg/120px-100_views_edo_020.jpg"
 },
 {
   "painting_index": 21,
   "title": "Mount Atago in Shiba (芝愛宕山, *Shiba Atagoyama*)",
   "depicted": "Atago Shrine, Edo Bay",
   "remarks": "Scene depicts an emissary from Enpuku-ji temple who on every third day of the year performs a ceremony at Atago Shrine for good fortune, health and success and to avert hunger and disease; the large rice paddle in his hand symbolizes abundance, the seaweed around his neck was distributed after the ceremony among the faithful who used it to brew an infusion against colds",
   "date_of_painting": "1857-08",
   "latitude": 35.664778,
   "longitude": 139.748444,
   "imagethumb": "f/fa/100_views_edo_021.jpg",
   "image": "f/fa/100_views_edo_021.jpg/120px-100_views_edo_021.jpg"
 },
 {
   "painting_index": 22,
   "title": "Hiroo on Furukawa River (広尾ふる川, *Hiroo Furukawa*)",
   "depicted": "Furukawa River, \"Fox\" (kitsune) restaurant",
   "remarks": "—",
   "date_of_painting": "1856-07",
   "latitude": 35.647139,
   "longitude": 139.731611,
   "imagethumb": "0/04/100_views_edo_022.jpg",
   "image": "0/04/100_views_edo_022.jpg/120px-100_views_edo_022.jpg"
 },
 {
   "painting_index": 23,
   "title": "Chiyogaike Pond in Meguro (目黒千代か池川, *Meguro Chiyogaike*)",
   "depicted": "Chiyogaike Pond",
   "remarks": "Feature a — for the time — unusual depiction of reflections of the trees in the water",
   "date_of_painting": "1856-07",
   "latitude": 35.6375,
   "longitude": 139.71278,
   "imagethumb": "f/fd/100_views_edo_023.jpg",
   "image": "f/fd/100_views_edo_023.jpg/120px-100_views_edo_023.jpg"
 },
 {
   "painting_index": 24,
   "title": "New Fuji in Meguro (目黒新富士, *Meguro Shin-Fuji*)",
   "depicted": "Mita Aqueduct, Mount Fuji replica, Mount Fuji",
   "remarks": "Subject is a replica (one of many) of Mount Fuji erected in 1829 by Fuji worshippers",
   "date_of_painting": "1857-04",
   "latitude": 35.643472,
   "longitude": 139.704861,
   "imagethumb": "3/34/100_views_edo_024.jpg",
   "image": "3/34/100_views_edo_024.jpg/120px-100_views_edo_024.jpg"
 },
 {
   "painting_index": 25,
   "title": "The Original Fuji in Meguro (目黒元不二, *Meguro Moto-Fuji*)",
   "depicted": "Mount Fuji replica, Mount Fuji",
   "remarks": "Fuji replica erected in 1812 was at 12 m (39 ft) the tallest in Edo; this print was incorrectly placed in the spring section of the table of contents since the depicted cherry trees are in autumn foliage; spelling of \"Fuji\" in the title as (不二, lit. \"not two\") is thought to be a pun on the doubling of the mountain",
   "date_of_painting": "1857-04",
   "latitude": 35.64667,
   "longitude": 139.701028,
   "imagethumb": "0/0e/100_views_edo_025.jpg",
   "image": "0/0e/100_views_edo_025.jpg/120px-100_views_edo_025.jpg"
 },
 {
   "painting_index": 26,
   "title": "The \"Armour-Hanging Pine\" at Hakkeizaka Bluff (八景坂鎧掛松, *Hakkeizaka Yoroikakematsu*)",
   "depicted": "Tōkaidō, Edo Bay",
   "remarks": "Depicts a popular viewpoint of Edo Bay; according to legend, Minamoto no Yoshiie hung his armour on this tree in 1062; Hiroshige adapts the shape of the tree so that only a giant could have hung his armour on it",
   "date_of_painting": "1856-05",
   "latitude": 35.5885,
   "longitude": 139.726861,
   "imagethumb": "5/5c/100_views_edo_026.jpg",
   "image": "5/5c/100_views_edo_026.jpg/120px-100_views_edo_026.jpg"
 },
 {
   "painting_index": 27,
   "title": "Plum Orchard in Kamada (蒲田の梅園, *Kamada no umezono*)",
   "depicted": "Plum Orchard in Kamada",
   "remarks": "—",
   "date_of_painting": "1857-02",
   "latitude": 35.56472,
   "longitude": 139.72694,
   "imagethumb": "f/f9/100_views_edo_027.jpg",
   "image": "f/f9/100_views_edo_027.jpg/120px-100_views_edo_027.jpg"
 },
 {
   "painting_index": 28,
   "title": "Palace Hill in Shinagawa (品川御殿やま, *Shinagawa Gotenyama*)",
   "depicted": "Palace Hill",
   "remarks": "Depicts both a famous cherry blossom spot and the destruction of the landscape after removal of earth; the earth was used to build ramparts ( *daiba*) in the sea following Commodore Perry's arrival in Edo Bay in 1853",
   "date_of_painting": "1856-04",
   "latitude": 35.621028,
   "longitude": 139.7395,
   "imagethumb": "b/b0/100_views_edo_028.jpg",
   "image": "b/b0/100_views_edo_028.jpg/120px-100_views_edo_028.jpg"
 },
 {
   "painting_index": 29,
   "title": "Moto-Hachiman Shrine in Sunamura (砂むら元八まん, *Sunamura Moto-Hachiman*)",
   "depicted": "Torii of Moto-Hachiman Shrine, Edo Bay",
   "remarks": "—",
   "date_of_painting": "1856-04",
   "latitude": 35.669278,
   "longitude": 139.837667,
   "imagethumb": "9/9c/100_views_edo_029.jpg",
   "image": "9/9c/100_views_edo_029.jpg/120px-100_views_edo_029.jpg"
 },
 {
   "painting_index": 30,
   "title": "Plum Park in Kameido (亀戸梅屋舗, *Kameido Umeyashiki*)",
   "depicted": "Plum Park in Kameido",
   "remarks": "Both in color and theme this print is related to print no. 27 (*Plum Orchard in Kamada*); copied by Vincent van Gogh under the title *Japonaiserie: Flowering Plum Tree*",
   "date_of_painting": "1857-11",
   "latitude": 35.704528,
   "longitude": 139.823917,
   "imagethumb": "a/a8/De_pruimenboomgaard_te_Kameido-Rijksmuseum_RP-P-1956-743.jpeg",
   "image": "a/a8/De_pruimenboomgaard_te_Kameido-Rijksmuseum_RP-P-1956-743.jpeg/120px-De_pruimenboomgaard_te_Kameido-Rijksmuseum_RP-P-1956-743.jpeg"
 },
 {
   "painting_index": 31,
   "title": "Azuma no mori Shrine and the Entwined Camphor (吾嬬の森連理の梓, *Azuma no mori Renri no azusa*)",
   "depicted": "Azuma Shrine",
   "remarks": "—",
   "date_of_painting": "1856-07",
   "latitude": 35.705528,
   "longitude": 139.826778,
   "imagethumb": "0/0e/100_views_edo_031.jpg",
   "image": "0/0e/100_views_edo_031.jpg/120px-100_views_edo_031.jpg"
 },
 {
   "painting_index": 32,
   "title": "The Yanagishima (柳しま, *Yanagishima*)",
   "depicted": "Myōken Hall of Hōshō-ji temple, Hashimotoya restaurant (\"At the Foot of the Bridge\"), Mount Tsukuba",
   "remarks": "—",
   "date_of_painting": "1857-04",
   "latitude": 35.707583,
   "longitude": 139.818306,
   "imagethumb": "3/31/100_views_edo_032.jpg",
   "image": "3/31/100_views_edo_032.jpg/120px-100_views_edo_032.jpg"
 },
 {
   "painting_index": 33,
   "title": "Towboats Along the Yotsugi-dōri Canal (四ツ木通用水引ふね, *Yotsugi dōri yōsui hikifune*)",
   "depicted": "Yotsugi-dōri Canal",
   "remarks": "Unlike in the print, the canal was absolutely straight",
   "date_of_painting": "1857-02",
   "latitude": 35.735472,
   "longitude": 139.83444,
   "imagethumb": "3/38/100_views_edo_033.jpg",
   "image": "3/38/100_views_edo_033.jpg/120px-100_views_edo_033.jpg"
 },
 {
   "painting_index": 34,
   "title": "Night View of Matsuchiyama and the San'ya Canal (真乳山山谷堀夜景, *Matsuchiyama San'yabori yakei*)",
   "depicted": "Sumida River, San'ya Canal inlet, Yumeiro and Takeya restaurants, Matsuchiyama hill, Shōten Shrine",
   "remarks": "Only image in the series to depict a large human figure, purportedly the favourite geisha of Hiroshige; Shōten Shrine on the top of the hill has sexual connotations",
   "date_of_painting": "1857-08",
   "latitude": 35.715917,
   "longitude": 139.806472,
   "imagethumb": "7/74/100_views_edo_034.jpg",
   "image": "7/74/100_views_edo_034.jpg/120px-100_views_edo_034.jpg"
 },
 {
   "painting_index": 35,
   "title": "Suijin Shrine and Massaki on the Sumida River (隅田川水神の森真崎, *Sumidagawa Suijin no mori Massaki*)",
   "depicted": "Cherry tree trunk, Suijin Shrine, Sumida River, Massaki district, Mount Tsukuba",
   "remarks": "People at the bottom of the print are on the way to the Hashiba ferry (see no. 37)",
   "date_of_painting": "1856-08",
   "latitude": 35.73278,
   "longitude": 139.812722,
   "imagethumb": "e/e1/100_views_edo_035.jpg",
   "image": "e/e1/100_views_edo_035.jpg/120px-100_views_edo_035.jpg"
 },
 {
   "painting_index": 36,
   "title": "View From Massaki of Suijin Shrine, Uchigawa Inlet, and Sekiya (真崎辺より水神の森内川関屋の里を見る図, *Massaki atari yori Suijin no mori Uchigawa Sekiya no sato wo miru zu*)",
   "depicted": "Sumida River, Suijin Shrine, Massaki district, Mount Tsukuba",
   "remarks": "Similar subject and location as no. 35",
   "date_of_painting": "1857-08",
   "latitude": 35.72972,
   "longitude": 139.808417,
   "imagethumb": "c/cb/100_views_edo_036.jpg",
   "image": "c/cb/100_views_edo_036.jpg/120px-100_views_edo_036.jpg"
 },
 {
   "painting_index": 37,
   "title": "Kilns and the Hashiba Ferry on the Sumida River (墨田河橋場の渡かわら竈, *Sumidagawa hashiba no watashi kawaragama*)",
   "depicted": "Kilns, Sumida River, Suijin Shrine, Mount Tsukuba",
   "remarks": "Similar area as no. 35, 36",
   "date_of_painting": "1857-04",
   "latitude": 35.72806,
   "longitude": 139.80972,
   "imagethumb": "4/4c/100_views_edo_037.jpg",
   "image": "4/4c/100_views_edo_037.jpg/120px-100_views_edo_037.jpg"
 },
 {
   "painting_index": 38,
   "title": "Dawn Inside the Yoshiwara (廓中東雲, *Kakuchū shinonome*)",
   "depicted": "Yoshiwara",
   "remarks": "Published two months prior to the reopening of Yoshiwara after it burnt down in the 1855 earthquake; Hiroshige may have submitted this design andtitle following the suicide of two courtesans and their two lovers at dawn of the 19th day of the 4th month of 1857",
   "date_of_painting": "1857-04",
   "latitude": 35.724222,
   "longitude": 139.796083,
   "imagethumb": "5/56/100_views_edo_038.jpg",
   "image": "5/56/100_views_edo_038.jpg/120px-100_views_edo_038.jpg"
 },
 {
   "painting_index": 39,
   "title": "Distant View of Kinryūzan Temple and the Azuma Bridge (吾妻橋金龍山遠望, *Azumabashi Kinryūzan enbo*)",
   "depicted": "Sumida River, Azuma Bridge, Kinryūzan Temple, Mount Fuji",
   "remarks": "—",
   "date_of_painting": "1857-08",
   "latitude": 35.71444,
   "longitude": 139.80417,
   "imagethumb": "1/1c/100_views_edo_039.jpg",
   "image": "1/1c/100_views_edo_039.jpg/120px-100_views_edo_039.jpg"
 },
 {
   "painting_index": 40,
   "title": "Bashō's Hermitage on Camellia Hill beside the Aqueduct at Sekiguchi (せき口上水端はせを庵椿やま, *Sekiguchi jōsuibata Bashōan Tsubakiyama*)",
   "depicted": "Sekiguchi Aqueduct, Bashō's Hermitage",
   "remarks": "—",
   "date_of_painting": "1857-04",
   "latitude": 35.712306,
   "longitude": 139.7235,
   "imagethumb": "9/98/100_views_edo_040.jpg",
   "image": "9/98/100_views_edo_040.jpg/120px-100_views_edo_040.jpg"
 },
 {
   "painting_index": 41,
   "title": "Hachiman Shrine in Ichigaya (市ヶ谷八幡, *Ichigaya Hachiman*)",
   "depicted": "Ichigaya moat, shopping street, Hachiman Shrine",
   "remarks": "Dated one month after Hiroshige's death and therefore attributed to Hiroshige II by some art historians",
   "date_of_painting": "1858-10",
   "latitude": 35.692722,
   "longitude": 139.73375,
   "imagethumb": "f/fa/100_views_edo_041.jpg",
   "image": "f/fa/100_views_edo_041.jpg/120px-100_views_edo_041.jpg"
 },
 {
   "painting_index": 42,
   "title": "Cherry Blossoms on the Banks of the Tama River (玉川堤の花, *Tamagawa tsutsumi no hana*)",
   "depicted": "Actually, the Tama River-Jōsui channel is depicted, with cherry trees far outside Edo",
   "remarks": "One of the first five prints sanctioned by the censors",
   "date_of_painting": "1856-02",
   "latitude": 35.689333,
   "longitude": 139.70222,
   "imagethumb": "4/4e/100_views_edo_042.jpg",
   "image": "4/4e/100_views_edo_042.jpg/120px-100_views_edo_042.jpg"
 },
 {
   "painting_index": 43,
   "title": "Nihonbashi Bridge and Edobashi Bridge (日本橋江戸ばし, *Nihonbashi Edobashi*)",
   "depicted": "Nihonbashi, Nihonbashi River, Edobashi",
   "remarks": "Fish barrel with first bonito of the season represents early summer",
   "date_of_painting": "1857-12",
   "latitude": 35.684222,
   "longitude": 139.774667,
   "imagethumb": "c/cc/100_views_edo_043.jpg",
   "image": "c/cc/100_views_edo_043.jpg/120px-100_views_edo_043.jpg"
 },
 {
   "painting_index": 44,
   "title": "View of Nihonbashi itchōme Street (日本橋通一丁目略図, *Nihonbashi Tōri itchōme ryakuzu*)",
   "depicted": "Nihonbashi itchōme Street",
   "remarks": "Shirokiya shop on the right developed into one of the city's largest department stores and finally became part of the Tokyu Group",
   "date_of_painting": "1858-08",
   "latitude": 35.6825,
   "longitude": 139.77325,
   "imagethumb": "5/5f/100_views_edo_044.jpg",
   "image": "5/5f/100_views_edo_044.jpg/120px-100_views_edo_044.jpg"
 },
 {
   "painting_index": 45,
   "title": "Yatsumi Bridge (八ツ見のはし, *Yatsumi no hashi*)",
   "depicted": "Yatsumi Bridge, Edo Castle, Mount Fuji",
   "remarks": "—",
   "date_of_painting": "1856-08",
   "latitude": 35.684639,
   "longitude": 139.771333,
   "imagethumb": "f/fd/100_views_edo_062.jpg",
   "image": "f/fd/100_views_edo_062.jpg/120px-100_views_edo_062.jpg"
 },
 {
   "painting_index": 46,
   "title": "Yoroi Ferry, Koami-chō (鎧の渡し小網町, *Yoroi no watashi Koami-chō*)",
   "depicted": "Nihonbashi River, Yoroi ferry",
   "remarks": "—",
   "date_of_painting": "1857-10",
   "latitude": 35.68225,
   "longitude": 139.779972,
   "imagethumb": "7/77/100_views_edo_045.jpg",
   "image": "7/77/100_views_edo_045.jpg/120px-100_views_edo_045.jpg"
 },
 {
   "painting_index": 47,
   "title": "Seidō and Kanda River from Shōhei Bridge (昌平橋聖堂神田川, *Shōheibashi Seidō Kandagawa*)",
   "depicted": "Shōhei Bridge, Shōheizaka hill, Kanda River, wall of Yushima Seidō",
   "remarks": "Exaggerated size of hill on left",
   "date_of_painting": "1857-09",
   "latitude": 35.69833,
   "longitude": 139.76889,
   "imagethumb": "9/97/100_views_edo_046.jpg",
   "image": "9/97/100_views_edo_046.jpg/120px-100_views_edo_046.jpg"
 },
 {
   "painting_index": 48,
   "title": "Suidō Bridge and the Surugadai Quarter (水道橋駿河台, *Suidōbashi Surugadai*)",
   "depicted": "View from Surugadai, Kanda River, Suidō Bridge, Edo Castle, Mount Fuji",
   "remarks": "Koinobori carp streamers place the scene around the Boy's festival on the 5th day of the 5th month, the same month as the print was approved by the censors",
   "date_of_painting": "1857-05",
   "latitude": 35.702083,
   "longitude": 139.75528,
   "imagethumb": "1/11/100_views_edo_063.jpg",
   "image": "1/11/100_views_edo_063.jpg/120px-100_views_edo_063.jpg"
 },
 {
   "painting_index": 49,
   "title": "Fudō Falls in Ōji (王子不動之滝, *Ōji Fudō no taki*)",
   "depicted": "Fudō Falls",
   "remarks": "Hasegawa Settan",
   "date_of_painting": "1857-09",
   "latitude": 35.75167,
   "longitude": 139.7335,
   "imagethumb": "b/b2/100_views_edo_047.jpg",
   "image": "b/b2/100_views_edo_047.jpg/120px-100_views_edo_047.jpg"
 },
 {
   "painting_index": 50,
   "title": "Kumano Jūnisha Shrine at Tsunohazu, known as \"Jūnisō\" (角筈熊野十二社 俗称十二そう, *Tsunohazu Kumano Jūnisha zokushō Jūnisō*)",
   "depicted": "Kumano Jūnisha Shrine",
   "remarks": "—",
   "date_of_painting": "1856-07",
   "latitude": 35.690322,
   "longitude": 139.688279,
   "imagethumb": "3/30/Hiroshige%2C_Kumanoj%C5%ABnisha_Shrine%2C_1856.jpg",
   "image": "3/30/Hiroshige%2C_Kumanoj%C5%ABnisha_Shrine%2C_1856.jpg/120px-Hiroshige%2C_Kumanoj%C5%ABnisha_Shrine%2C_1856.jpg"
 },
 {
   "painting_index": 51,
   "title": "The Sannō Festival Procession at Kōjimachi itchōme (糀町一丁目山王祭ねり込, *Kōjimachi itchōme Sannō Matsuri nerikomi*)",
   "depicted": "Moat and Hanzōmon Gate of Edo Castle",
   "remarks": "Sannō Festival was held one month prior to the approval of the print",
   "date_of_painting": "1856-07",
   "latitude": 35.68139,
   "longitude": 139.744861,
   "imagethumb": "a/a8/100_views_edo_065.jpg",
   "image": "a/a8/100_views_edo_065.jpg/120px-100_views_edo_065.jpg"
 },
 {
   "painting_index": 52,
   "title": "The Paulownia Garden at Akasaka (赤坂桐畑, *Akasaka Kiribatake*)",
   "depicted": "Paulownia Garden, Tameike Pond, Hie Shrine, residence of *daimyō* Kuroda from Fukuoka",
   "remarks": "Hie Shrine is location for the Sannō Festival (see no. 51)",
   "date_of_painting": "1856-04",
   "latitude": 35.67417,
   "longitude": 139.737917,
   "imagethumb": "b/bd/100_views_edo_048.jpg",
   "image": "b/bd/100_views_edo_048.jpg/120px-100_views_edo_048.jpg"
 },
 {
   "painting_index": 53,
   "title": "The Pagoda of Zōjōji Temple and Akabane (増上寺塔赤羽根, *Zōjōjitō Akabane*)",
   "depicted": "Zōjō-ji, Akabane Bridge, residence of *daimyō* Arima from Kurume",
   "remarks": "—",
   "date_of_painting": "1857-01",
   "latitude": 35.654639,
   "longitude": 139.7475,
   "imagethumb": "d/dd/100_views_edo_049.jpg",
   "image": "d/dd/100_views_edo_049.jpg/120px-100_views_edo_049.jpg"
 },
 {
   "painting_index": 54,
   "title": "The Benkei Moat from Soto-Sakurada to Kōjimachi (外桜田弁慶堀糀町, *Soto-Sakurada Benkeibori Kōjimachi*)",
   "depicted": "South-west embankment and moat of Edo Castle, residence of *daimyō* Ii from the Hikone Domain, Kōjimachi watchtower",
   "remarks": "Kōjimachi watchtower had been restored two months prior to publication after burning down in the 1855 earthquake",
   "date_of_painting": "1856-05",
   "latitude": 35.677306,
   "longitude": 139.750611,
   "imagethumb": "6/61/100_views_edo_066.jpg",
   "image": "6/61/100_views_edo_066.jpg/120px-100_views_edo_066.jpg"
 },
 {
   "painting_index": 55,
   "title": "The Sumiyoshi Festival at Tsukudajima (佃しま住吉の祭, *Tsukudajima Sumiyoshi no matsuri*)",
   "depicted": "Tsukudajima Island",
   "remarks": "The Sumiyoshi Festival is held on the 29th of the sixth month, i.e., in the month prior to publication of this print; writer of the inscription is identified on the banner as the creator of the table of contents of this series, Seikengū Gengyo",
   "date_of_painting": "1857-07",
   "latitude": 35.668,
   "longitude": 139.78333,
   "imagethumb": "7/74/Hiroshige%2C_Sumiyoshi_festival%2C_Tsukudajima%2C_1857.jpg",
   "image": "7/74/Hiroshige%2C_Sumiyoshi_festival%2C_Tsukudajima%2C_1857.jpg/120px-Hiroshige%2C_Sumiyoshi_festival%2C_Tsukudajima%2C_1857.jpg"
 },
 {
   "painting_index": 56,
   "title": "Mannen Bridge in Fukagawa (深川萬年橋, *Fukagawa Mannenbashi*)",
   "depicted": "Mannen Bridge, Mount Fuji",
   "remarks": "—",
   "date_of_painting": "1857-11",
   "latitude": 35.683472,
   "longitude": 139.794111,
   "imagethumb": "2/2b/100_views_edo_051.jpg",
   "image": "2/2b/100_views_edo_051.jpg/120px-100_views_edo_051.jpg"
 },
 {
   "painting_index": 57,
   "title": "Mitsumata Wakarenofuchi (みつまたわかれの淵)",
   "depicted": "Sumida River, Mount Fuji",
   "remarks": "Reed-covered sandbank alludes to the artificial Nakazu island, location of a famous 18th-century pleasure district that was demolished in the course of the Kansei Reforms",
   "date_of_painting": "1857-02",
   "latitude": 35.682028,
   "longitude": 139.79083,
   "imagethumb": "0/06/100_views_edo_067.jpg",
   "image": "0/06/100_views_edo_067.jpg/120px-100_views_edo_067.jpg"
 },
 {
   "painting_index": 58,
   "title": "Sudden Shower over Shin-Ōhashi bridge and Atake (大はしあたけの夕立, *Ōhashi atake no yūdachi*)",
   "depicted": "Shin-Ōhashi bridge, Sumida River, Atake district",
   "remarks": "Considered to be a masterpiece and possibly Hiroshige's most famous work; copied by Vincent van Gogh",
   "date_of_painting": "1857-09",
   "latitude": 35.68528,
   "longitude": 139.79306,
   "imagethumb": "7/72/Hiroshige%2C_Sudden_shower_over_Shin-%C5%8Chashi_bridge_and_Atake%2C_1857.jpg",
   "image": "7/72/Hiroshige%2C_Sudden_shower_over_Shin-%C5%8Chashi_bridge_and_Atake%2C_1857.jpg/120px-Hiroshige%2C_Sudden_shower_over_Shin-%C5%8Chashi_bridge_and_Atake%2C_1857.jpg"
 },
 {
   "painting_index": 59,
   "title": "Ryōgoku Bridge and the Great Riverbank (両国橋大川ばた, *Ryōgokubashi Ōkawabata*)",
   "depicted": "Sumida River, Ryōgoku Bridge",
   "remarks": "At the time Japan's largest bridge",
   "date_of_painting": "1856-08",
   "latitude": 35.69306,
   "longitude": 139.787694,
   "imagethumb": "d/dc/Brooklyn_Museum_-_Ryogoku_Bridge_and_the_Great_Riverbank_No_59_from_One_Hundred_Views_of_Edo_-_Utagawa_Hiroshige_%28Ando%29.jpg",
   "image": "d/dc/Brooklyn_Museum_-_Ryogoku_Bridge_and_the_Great_Riverbank_No_59_from_One_Hundred_Views_of_Edo_-_Utagawa_Hiroshige_%28Ando%29.jpg/120px-Brooklyn_Museum_-_Ryogoku_Bridge_and_the_Great_Riverbank_No_59_from_One_Hundred_Views_of_Edo_-_Utagawa_Hiroshige_%28Ando%29.jpg"
 },
 {
   "painting_index": 60,
   "title": "Asakusa River, Miyato River, Great Riverbank (浅草川大川端宮戸川, *Asakusagawa Ōkawabata Miyatogawa*)",
   "depicted": "Sumida River, Mount Tsukuba",
   "remarks": "Depicts pilgrimage to Mount Ōyama, the pilgrim's return from the mountain is shown in no. 76; names in title are synonymous names for the depicted section of the Sumida River; in later prints, the title was simplified to: *In Boats at Ryōgoku with a distant View of Asakusa*",
   "date_of_painting": "1857-07",
   "latitude": 35.693972,
   "longitude": 139.787889,
   "imagethumb": "f/fc/100_views_edo_068.jpg",
   "image": "f/fc/100_views_edo_068.jpg/120px-100_views_edo_068.jpg"
 },
 {
   "painting_index": 61,
   "title": "The \"Pine of Success\" and Oumayagashi on the Asakusa River (浅草川首尾の松御厩河岸, *Asakusagawa shubi no matsu Oumayagashi*)",
   "depicted": "Sumida River, Oumayagashi ferry",
   "remarks": "Hiroshige's \"Illustrated Souvenirs of Edo\" contains a mirror image of this view with a woman standing upright in the boat",
   "date_of_painting": "1856-08",
   "latitude": 35.70056,
   "longitude": 139.792167,
   "imagethumb": "a/a9/100_views_edo_oumaya.jpg",
   "image": "a/a9/100_views_edo_oumaya.jpg/120px-100_views_edo_oumaya.jpg"
 },
 {
   "painting_index": 62,
   "title": "Komakata Hall and Azuma Bridge (駒形堂吾嬬橋, *Komakatadō Azumabashi*)",
   "depicted": "Komakata Hall, Sumida River, Azuma Bridge, Asakusa district",
   "remarks": "Lesser cuckoo (*hototogisu*) and Komakata Hall in the print allude to a 17th-century love poem attributed to Takao II, courtesan and lover of Date Tsunamune: Are you now, my love, near Komakata? Cry of the cuckoo!\"[nb 3]",
   "date_of_painting": "1857-01",
   "latitude": 35.708972,
   "longitude": 139.79675,
   "imagethumb": "3/31/100_views_edo_055.jpg",
   "image": "3/31/100_views_edo_055.jpg/120px-100_views_edo_055.jpg"
 },
 {
   "painting_index": 63,
   "title": "The Ayase River and Kanegafuchi (綾瀬川鐘か淵, *Ayasegawa Kanegafuchi*)",
   "depicted": "Sumida River, Ayase River",
   "remarks": "Northernmost point of the Sumida river depicted in this series",
   "date_of_painting": "1857-01",
   "latitude": 35.73972,
   "longitude": 139.81528,
   "imagethumb": "b/bf/100_views_edo_069.jpg",
   "image": "b/bf/100_views_edo_069.jpg/120px-100_views_edo_069.jpg"
 },
 {
   "painting_index": 64,
   "title": "Horikiri Iris Garden (堀切の花菖蒲, *Horikiri no hanashōbu*)",
   "depicted": "Horikiri Iris Garden",
   "remarks": "Influenced European Art Nouveau",
   "date_of_painting": "1857-05",
   "latitude": 35.731056,
   "longitude": 139.766028,
   "imagethumb": "8/8b/Hiroshige%2C_Horikiri_iris_garden%2C_1857.jpg",
   "image": "8/8b/Hiroshige%2C_Horikiri_iris_garden%2C_1857.jpg/120px-Hiroshige%2C_Horikiri_iris_garden%2C_1857.jpg"
 },
 {
   "painting_index": 65,
   "title": "Inside Kameido Tenjin Shrine (亀戸天神境内, *Kameidō Tenjin keidai*)",
   "depicted": "Drum bridge and garden at Kameido Tenjin Shrine",
   "remarks": "Flowering wisteria indicates summer season",
   "date_of_painting": "1856-07",
   "latitude": 35.702194,
   "longitude": 139.820972,
   "imagethumb": "a/a3/100_views_edo_057.jpg",
   "image": "a/a3/100_views_edo_057.jpg/120px-100_views_edo_057.jpg"
 },
 {
   "painting_index": 66,
   "title": "The Sazaidō Hall at the Five Hundred Rakan Temple (五百羅漢さゞゐ堂, *Gohyaku Rakan Sazaidō*)",
   "depicted": "Sazaidō Hall",
   "remarks": "—",
   "date_of_painting": "1857-08",
   "latitude": 35.689583,
   "longitude": 139.82667,
   "imagethumb": "4/44/100_views_edo_070.jpg",
   "image": "4/44/100_views_edo_070.jpg/120px-100_views_edo_070.jpg"
 },
 {
   "painting_index": 67,
   "title": "The Ferry at Sakasai (逆井のわたし, *Sasakai no watashi*)",
   "depicted": "Nakagawa River",
   "remarks": "—",
   "date_of_painting": "1857-02",
   "latitude": 35.695139,
   "longitude": 139.847583,
   "imagethumb": "b/b6/100_views_edo_058.jpg",
   "image": "b/b6/100_views_edo_058.jpg/120px-100_views_edo_058.jpg"
 },
 {
   "painting_index": 68,
   "title": "Open Garden at the Hachiman Shrine in Fukagawa (深川八まん山ひらき, *Fukagawa Hachiman yamahiraki*)",
   "depicted": "Garden at Hachiman Shrine",
   "remarks": "Print shows both azaleas and cherry trees in blossom which is unnatural for scattered all over Edo",
   "date_of_painting": "1857-08",
   "latitude": 35.67306,
   "longitude": 139.7975,
   "imagethumb": "e/e6/100_views_edo_059.jpg",
   "image": "e/e6/100_views_edo_059.jpg/120px-100_views_edo_059.jpg"
 },
 {
   "painting_index": 69,
   "title": "Sanjusangendō Hall in Fukagawa (深川三十三間堂, *Fukagawa Sanjusangendō*)",
   "depicted": "Sanjusangendō, Kiba lumberyards (see no. 106)",
   "remarks": "About half of the hall is depicted",
   "date_of_painting": "1857-08",
   "latitude": 35.671639,
   "longitude": 139.801472,
   "imagethumb": "3/36/100_views_edo_071.jpg",
   "image": "3/36/100_views_edo_071.jpg/120px-100_views_edo_071.jpg"
 },
 {
   "painting_index": 70,
   "title": "The mouth of the Nakagawa River (中川口, *Nakagawaguchi*)",
   "depicted": "Onagigawa Canal, Nakagawa River, Shinkawa Canal",
   "remarks": "Nakagawa River is the broad waterway in the middle running left-right[nb 4]",
   "date_of_painting": "1857-02",
   "latitude": 35.68639,
   "longitude": 139.84667,
   "imagethumb": "4/48/100_views_edo_060.jpg",
   "image": "4/48/100_views_edo_060.jpg/120px-100_views_edo_060.jpg"
 },
 {
   "painting_index": 71,
   "title": "Scattered Pines on the Tone River (利根川ばらばらまつ, *Tonegawa barabara-matsu*)",
   "depicted": "Tone River",
   "remarks": "—",
   "date_of_painting": "1856-08",
   "latitude": 35.67778,
   "longitude": 139.88639,
   "imagethumb": "5/5c/100_views_edo_061.jpg",
   "image": "5/5c/100_views_edo_061.jpg/120px-100_views_edo_061.jpg"
 },
 {
   "painting_index": 72,
   "title": "The Ferry at Haneda and the Benten Shrine (はねたのわたし弁天の社, *Haneda no watashi Benten no yashiro*)",
   "depicted": "Tama River, Benten Shrine, Edo Bay",
   "remarks": "The ground of the Benten Shrine is now occupied by Haneda Airport",
   "date_of_painting": "1858-08",
   "latitude": 35.54333,
   "longitude": 139.74306,
   "imagethumb": "6/62/100_views_edo_072.jpg",
   "image": "6/62/100_views_edo_072.jpg/120px-100_views_edo_072.jpg"
 },
 {
   "painting_index": 73,
   "title": "The City Flourishing, the Tanabata Festival (市中繁栄七夕祭, *Shichū han'ei Tanabata matsuri*)",
   "depicted": "Edo Castle, Mount Fuji",
   "remarks": "Arguably shows the view from Hiroshige's house; only print in series without a place name in the title",
   "date_of_painting": "1857-07",
   "latitude": 35.67806,
   "longitude": 139.7725,
   "imagethumb": "3/36/100_views_edo_073.jpg",
   "image": "3/36/100_views_edo_073.jpg/120px-100_views_edo_073.jpg"
 },
 {
   "painting_index": 74,
   "title": "Silk Shops in Ōdenma-chō (大伝馬町ごふく店, *Ōdenma-chō gofukudana*)",
   "depicted": "Daimaru silk merchant shops",
   "remarks": "People depicted are carpenters",
   "date_of_painting": "1858-07",
   "latitude": 35.690639,
   "longitude": 139.78025,
   "imagethumb": "d/dd/100_views_edo_074.jpg",
   "image": "d/dd/100_views_edo_074.jpg/120px-100_views_edo_074.jpg"
 },
 {
   "painting_index": 75,
   "title": "The Dyers' Quarter in Kanda (神田紺屋町, *Kanda konya-chō*)",
   "depicted": "Kanda dye works, Edo Castle, Mount Fuji",
   "remarks": "Kanji on first two white-blue fabrics reads \"sakana\" and is a reference to the publisher Sakanaya Eikichi, last two white-blue fabrics contain Hiroshige's monogram",
   "date_of_painting": "1857-11",
   "latitude": 35.69167,
   "longitude": 139.77444,
   "imagethumb": "1/16/Hiroshige_Le_quartier_des_teinturiers_de_Kanda.jpg",
   "image": "1/16/Hiroshige_Le_quartier_des_teinturiers_de_Kanda.jpg/120px-Hiroshige_Le_quartier_des_teinturiers_de_Kanda.jpg"
 },
 {
   "painting_index": 76,
   "title": "Bamboo Quay by Kyōbashi Bridge (京橋竹がし, *Kyōbashi Takegashi*)",
   "depicted": "Kyōbashi River, Kyōbashi Bridge",
   "remarks": "—",
   "date_of_painting": "1857-12",
   "latitude": 35.675083,
   "longitude": 139.769028,
   "imagethumb": "a/a4/100_views_edo_076.jpg",
   "image": "a/a4/100_views_edo_076.jpg/120px-100_views_edo_076.jpg"
 },
 {
   "painting_index": 77,
   "title": "Inari Bridge and the Minato Shrine in Teppōzu (鉄砲洲稲荷橋湊神社, *Teppōzu Inaribashi Minato jinja*)",
   "depicted": "Hatchōbori Canal, Minato Shrine, Inari Bridge, Mount Fuji",
   "remarks": "—",
   "date_of_painting": "1857-02",
   "latitude": 35.67375,
   "longitude": 139.780139,
   "imagethumb": "d/db/100_views_edo_077.jpg",
   "image": "d/db/100_views_edo_077.jpg/120px-100_views_edo_077.jpg"
 },
 {
   "painting_index": 78,
   "title": "Teppōzu and Tsukiji Monzeki Temple (鉄砲洲築地門跡, *Teppōzu Tsukiji Monzeki*)",
   "depicted": "Sumida River, Tsukiji Hongan-ji Temple",
   "remarks": "Like no. 79, this print has the changed series title: *Entertaining Supplements to the One Hundred Famous Views of Edo*, as likely Hiroshige wanted to end this series having produced 110 plates already at the time; he resumed the original title on the publisher insisting to do so",
   "date_of_painting": "1858-07",
   "latitude": 35.66667,
   "longitude": 139.780694,
   "imagethumb": "1/19/100_views_edo_078.jpg",
   "image": "1/19/100_views_edo_078.jpg/120px-100_views_edo_078.jpg"
 },
 {
   "painting_index": 79,
   "title": "Shiba Shinmei Shrine and Zōjōji Temple (芝神明増上寺, *Shiba Shinmei Zōjōji*)",
   "depicted": "Shiba Shinmei Shrine, Zōjōji",
   "remarks": "—",
   "date_of_painting": "1858-07",
   "latitude": 35.656861,
   "longitude": 139.75417,
   "imagethumb": "4/45/100_views_edo_079.jpg",
   "image": "4/45/100_views_edo_079.jpg/120px-100_views_edo_079.jpg"
 },
 {
   "painting_index": 80,
   "title": "Kanasugi Bridge and Shibaura (金杉橋芝浦, *Kanasugibashi Shibaura*)",
   "depicted": "Kanasugi Bridge",
   "remarks": "Print shows pilgrims of the Nichiren sect; brown and white cloths at bottom left contain abbreviation \"Uoei\" of the publisher's name Sakanaya Eikichi",
   "date_of_painting": "1857-07",
   "latitude": 35.65306,
   "longitude": 139.754056,
   "imagethumb": "7/7f/100_views_edo_080.jpg",
   "image": "7/7f/100_views_edo_080.jpg/120px-100_views_edo_080.jpg"
 },
 {
   "painting_index": 81,
   "title": "Ushimachi in Takanawa (高輪うしまち, *Takanawa ushimachi*)",
   "depicted": "Tōkaidō, Edo Bay with *daiba*",
   "remarks": "Place name Takanawa meaning \"high wheel\" is symbolized by the wheel on the right and the rainbow",
   "date_of_painting": "1857-04",
   "latitude": 35.63825,
   "longitude": 139.73972,
   "imagethumb": "3/37/100_views_edo_081.jpg",
   "image": "3/37/100_views_edo_081.jpg/120px-100_views_edo_081.jpg"
 },
 {
   "painting_index": 82,
   "title": "Moon Viewing (月の岬, *Tsuki no Misaki*)",
   "depicted": "Edo Bay",
   "remarks": "Approximately same view as no. 83",
   "date_of_painting": "1857-08",
   "latitude": 35.62194,
   "longitude": 139.740417,
   "imagethumb": "5/57/100_views_edo_082.jpg",
   "image": "5/57/100_views_edo_082.jpg/120px-100_views_edo_082.jpg"
 },
 {
   "painting_index": 83,
   "title": "Shinagawa Susaki (品川すさき)",
   "depicted": "Meguro River, Benten Shrine, Edo Bay with *daiba*",
   "remarks": "Establishment depicted in no. 82 might be the one cropped in the bottom left of this print",
   "date_of_painting": "1856-04",
   "latitude": 35.621278,
   "longitude": 139.742333,
   "imagethumb": "0/0d/100_views_edo_083.jpg",
   "image": "0/0d/100_views_edo_083.jpg/120px-100_views_edo_083.jpg"
 },
 {
   "painting_index": 84,
   "title": "\"Grandpa's Teahouse\" in Meguro (目黒爺々が茶屋, *Meguro jijigachaya*)",
   "depicted": "Teahouse and teastall, Mount Fuji",
   "remarks": "—",
   "date_of_painting": "1857-04",
   "latitude": 35.640167,
   "longitude": 139.709111,
   "imagethumb": "d/d6/100_views_edo_084.jpg",
   "image": "d/d6/100_views_edo_084.jpg/120px-100_views_edo_084.jpg"
 },
 {
   "painting_index": 85,
   "title": "Kinokuni Hill and Distant View of Akasaka and the Tameike Pond (紀ノ国坂赤坂溜池遠景, *Kinokunizaka Akasaka Tameike enkei*)",
   "depicted": "outer Benkeibori moat of Edo Castle",
   "remarks": "People depicted are samurai",
   "date_of_painting": "1857-09",
   "latitude": 35.679583,
   "longitude": 139.7325,
   "imagethumb": "e/ef/100_views_edo_085.jpg",
   "image": "e/ef/100_views_edo_085.jpg/120px-100_views_edo_085.jpg"
 },
 {
   "painting_index": 86,
   "title": "Naitō Shinjuku in Yotsuya (四ッ谷内藤新宿, *Yotsuya Naitō Shinjuku*)",
   "depicted": "Naitō Shinjuku (first station of the Kōshū Kaidō)",
   "remarks": "Depiction of horse dung was criticized for being vulgar; Hiroshige likely alludes to the quote: \"flowers thriving on the horse dung of Yotsuya\" from the 1775 book *Master Flashgold's Splendiferous Dream* referring to the prostitutes of Shinjuku",
   "date_of_painting": "1857-11",
   "latitude": 35.689806,
   "longitude": 139.707083,
   "imagethumb": "a/a3/100_views_edo_086.jpg",
   "image": "a/a3/100_views_edo_086.jpg/120px-100_views_edo_086.jpg"
 },
 {
   "painting_index": 87,
   "title": "Benten Shrine at the Inokashira Pond (井の頭の池弁天の社, *Inokashira no ike Benten no yashiro*)",
   "depicted": "Benten Shrine, Inokashira Pond",
   "remarks": "Depicts most western point of the series and location furthest away from central Edo",
   "date_of_painting": "1856-04",
   "latitude": 35.699528,
   "longitude": 139.57475,
   "imagethumb": "7/7c/100_views_edo_087.jpg",
   "image": "7/7c/100_views_edo_087.jpg/120px-100_views_edo_087.jpg"
 },
 {
   "painting_index": 88,
   "title": "Takinogawa in Ōji (王子滝の川, *Ōji Takinogawa*)",
   "depicted": "Takinogawa, Matsubashi Benten Shrine, Kongo-ji Temple",
   "remarks": "Original orange color of autumn color has turned brownish-black due to oxidation over time",
   "date_of_painting": "1856-04",
   "latitude": 35.752,
   "longitude": 139.729944,
   "imagethumb": "e/e3/100_views_edo_088.jpg",
   "image": "e/e3/100_views_edo_088.jpg/120px-100_views_edo_088.jpg"
 },
 {
   "painting_index": 89,
   "title": "\"Moon Pine\" in Ueno (上野山内月のまつ, *Ueno sannai Tsuki no matsu*)",
   "depicted": "Moon Pine, Shinobazu Pond, Benten Shrine",
   "remarks": "—",
   "date_of_painting": "1857-08",
   "latitude": 35.712472,
   "longitude": 139.773083,
   "imagethumb": "f/fb/100_views_edo_089.jpg",
   "image": "f/fb/100_views_edo_089.jpg/120px-100_views_edo_089.jpg"
 },
 {
   "painting_index": 90,
   "title": "Night View of Saruwaka-machi (猿わか町よるの景, *Saruwaka-machi yoru no kei*)",
   "depicted": "Saruwaka-chō street with theatres",
   "remarks": "Notable for the use of peoples' shadows giving the impression of puppets on a stage; the street was home to the Kabuki and marionette theatres",
   "date_of_painting": "1856-09",
   "latitude": 35.7175,
   "longitude": 139.800944,
   "imagethumb": "f/f0/Hiroshige%2C_Night_View_of_Saruwaka-machi.jpg",
   "image": "f/f0/Hiroshige%2C_Night_View_of_Saruwaka-machi.jpg/120px-Hiroshige%2C_Night_View_of_Saruwaka-machi.jpg"
 },
 {
   "painting_index": 91,
   "title": "In the Akiba Shrine at Ukeji (請地秋葉の境内, *Ukechi Akiba no keinai*)",
   "depicted": "Garden of Akiba Shrine",
   "remarks": "People depicted in the bottom left might be Hiroshige as a monk with painting utensils,[nb 5] his wife Yasu and their adopted daughter Tatsu according to Henry D. Smith",
   "date_of_painting": "1857-08",
   "latitude": 35.71694,
   "longitude": 139.812861,
   "imagethumb": "2/20/100_views_edo_091.jpg",
   "image": "2/20/100_views_edo_091.jpg/120px-100_views_edo_091.jpg"
 },
 {
   "painting_index": 92,
   "title": "Mokuboji Temple and Vegetable Fields on Uchigawa Inlet (木母寺内川御前栽畑, *Mokubōji Uchigawa Gozensaibata*)",
   "depicted": "Uchigawa inlet of Sumida River, Uekiya Han'emon restaurant",
   "remarks": "The Mokuboji temple mentioned in the title is close but not depicted in this print; Tokugawa Iesada had visited the restaurant one month before publication of the print",
   "date_of_painting": "1857-12",
   "latitude": 35.733944,
   "longitude": 139.81425,
   "imagethumb": "f/f3/100_views_edo_092.jpg",
   "image": "f/f3/100_views_edo_092.jpg/120px-100_views_edo_092.jpg"
 },
 {
   "painting_index": 93,
   "title": "Niijuku Ferry (にい宿のわたし, *Niijuku no watashi*)",
   "depicted": "Nakagawa River",
   "remarks": "Northeasternmost scene of the series confirmed by detailed depiction of the Edo side of the river and vagueness on the opposite bank",
   "date_of_painting": "1857-02",
   "latitude": 35.763167,
   "longitude": 139.854306,
   "imagethumb": "4/4d/100_views_edo_093.jpg",
   "image": "4/4d/100_views_edo_093.jpg/120px-100_views_edo_093.jpg"
 },
 {
   "painting_index": 94,
   "title": "The Maple Trees at Mama, the Tekona Shrine and Tsugihashi Bridge (真間の紅葉手古那の社継はし, *Mama no momiji Tekona no yashiro Tsugihashi*)",
   "depicted": "Edogawa River, Tekona Shrine, Tsugihashi Bridge",
   "remarks": "Original orange color of autumn color has turned brownish-black due to oxidation over time",
   "date_of_painting": "1857-01",
   "latitude": 35.73833,
   "longitude": 139.909222,
   "imagethumb": "1/11/100_views_edo_094.jpg",
   "image": "1/11/100_views_edo_094.jpg/120px-100_views_edo_094.jpg"
 },
 {
   "painting_index": 95,
   "title": "View of Kōnodai and the Tone River (鴻の台とね川風景, *Kōnodai Tonegawa Fūkei*)",
   "depicted": "Tone River (today Edogawa), Mount Fuji",
   "remarks": "—",
   "date_of_painting": "1856-05",
   "latitude": 35.74778,
   "longitude": 139.8975,
   "imagethumb": "b/bd/100_views_edo_095.jpg",
   "image": "b/bd/100_views_edo_095.jpg/120px-100_views_edo_095.jpg"
 },
 {
   "painting_index": 96,
   "title": "Horie and Nekozane (堀江ねこざね, *Horie Nekozane*)",
   "depicted": "branch of the Edogawa River, Horie and Nekozane villages, Edo Bay, Mount Fuji",
   "remarks": "One of the first five prints sanctioned by the censors",
   "date_of_painting": "1856-02",
   "latitude": 35.65917,
   "longitude": 139.89694,
   "imagethumb": "e/ee/100_views_edo_096.jpg",
   "image": "e/ee/100_views_edo_096.jpg/120px-100_views_edo_096.jpg"
 },
 {
   "painting_index": 97,
   "title": "\"Five Pines\" and the Onagi Canal (小奈木川五本まつ, *Ongagigawa Gohonmatsu*)",
   "depicted": "Onagi Canal",
   "remarks": "Tree depicted is the only surviving of five pines and was at the time of Hiroshige known as \"Five Pines\"; Onagi Canal was in fact straight",
   "date_of_painting": "1856-07",
   "latitude": 35.685139,
   "longitude": 139.81806,
   "imagethumb": "e/e7/100_views_edo_097.jpg",
   "image": "e/e7/100_views_edo_097.jpg/120px-100_views_edo_097.jpg"
 },
 {
   "painting_index": 98,
   "title": "Fireworks by Ryōgoku Bridge (両国花火, *Ryōgoku hanabi*)",
   "depicted": "Sumida River, Ryōgoku Bridge",
   "remarks": "—",
   "date_of_painting": "1858-08",
   "latitude": 35.693556,
   "longitude": 139.78875,
   "imagethumb": "e/e6/100_views_edo_098.jpg",
   "image": "e/e6/100_views_edo_098.jpg/120px-100_views_edo_098.jpg"
 },
 {
   "painting_index": 99,
   "title": "Kinryūzan Temple in Asakusa (浅草金龍山, *Asakusa Kinryūzan*)",
   "depicted": "Kaminarimon, Hōzōmon and pagoda of Sensō-ji",
   "remarks": "Thought to commemorate the restoration of the pagoda two month prior to the publication of the print after damage suffered in the 1855 earthquake",
   "date_of_painting": "1856-07",
   "latitude": 35.71111,
   "longitude": 139.79639,
   "imagethumb": "d/df/100_views_edo_099.jpg",
   "image": "d/df/100_views_edo_099.jpg/120px-100_views_edo_099.jpg"
 },
 {
   "painting_index": 100,
   "title": "Nihon Embankment and Yoshiwara (よし原日本堤, *Yoshiwara Nihondzutsumi*)",
   "depicted": "Nihon Embankment, Yoshiwara",
   "remarks": "—",
   "date_of_painting": "1857-04",
   "latitude": 35.724583,
   "longitude": 139.797278,
   "imagethumb": "e/e6/100_views_edo_100.jpg",
   "image": "e/e6/100_views_edo_100.jpg/120px-100_views_edo_100.jpg"
 },
 {
   "painting_index": 101,
   "title": "Asakusa Ricefields and Torinomachi Festival (浅草田甫酉の町詣, *Asakusa tanbu Torinomachi mōde*)",
   "depicted": "Yoshiwara teahouse, Chōkoku-ji temple (Ōtori Shrine), Mount Fuji",
   "remarks": "White cat represents courtesan who just finished her work; the festival of the rooster is hinted at by bear's paw hairpins resembling the good luck rakes carried by pilgrims in the background",
   "date_of_painting": "1857-11",
   "latitude": 35.7225,
   "longitude": 139.79194,
   "imagethumb": "d/d1/100_views_edo_101.jpg",
   "image": "d/d1/100_views_edo_101.jpg/120px-100_views_edo_101.jpg"
 },
 {
   "painting_index": 102,
   "title": "Minowa, Kanasugi and Mikawashima (蓑輪金杉三河しま, *Minowa Kanasugi Mikawashima*)",
   "depicted": "Minowa, Kanasugi and Mikawashima villages",
   "remarks": "—",
   "date_of_painting": "1857-05",
   "latitude": 35.73194,
   "longitude": 139.77944,
   "imagethumb": "f/f1/Hiroshige%2C_Minowa%2C_Kanasugi%2C_Mikawashima%2C_1857.jpg",
   "image": "f/f1/Hiroshige%2C_Minowa%2C_Kanasugi%2C_Mikawashima%2C_1857.jpg/120px-Hiroshige%2C_Minowa%2C_Kanasugi%2C_Mikawashima%2C_1857.jpg"
 },
 {
   "painting_index": 103,
   "title": "Senju Great Bridge (千住の大はし, *Senju no ōhashi*)",
   "depicted": "Arakawa River, Senju Great Bridge",
   "remarks": "One of the first five prints sanctioned by the censors",
   "date_of_painting": "1856-02",
   "latitude": 35.73944,
   "longitude": 139.7975,
   "imagethumb": "a/a0/100_views_edo_103.jpg",
   "image": "a/a0/100_views_edo_103.jpg/120px-100_views_edo_103.jpg"
 },
 {
   "painting_index": 104,
   "title": "Koume Embankment (小梅堤, *Koumetsutsumi*)",
   "depicted": "Yotsugi dōri Canal (see no. 33)",
   "remarks": "—",
   "date_of_painting": "1857-02",
   "latitude": 35.710639,
   "longitude": 139.80833,
   "imagethumb": "2/2b/100_views_edo_104.jpg",
   "image": "2/2b/100_views_edo_104.jpg/120px-100_views_edo_104.jpg"
 },
 {
   "painting_index": 105,
   "title": "Oumayagashi (御厩河岸)",
   "depicted": "Sumida River",
   "remarks": "The two women are *yotaka* (night hawks), the lowest class of prostitutes whose faces were often disfigured forcing them to apply very thick make-up",
   "date_of_painting": "1857-12",
   "latitude": 35.703667,
   "longitude": 139.793806,
   "imagethumb": "8/80/100_views_edo_105.jpg",
   "image": "8/80/100_views_edo_105.jpg/120px-100_views_edo_105.jpg"
 },
 {
   "painting_index": 106,
   "title": "The Fukagawa Lumberyards (深川木場, *Fukagawa kiba*)",
   "depicted": "Fukagawa Lumberyards",
   "remarks": "Character for \"sakana\" on the umbrella refers to Sakanaya Eikichi, the publisher of the series",
   "date_of_painting": "1856-08",
   "latitude": 35.67639,
   "longitude": 139.80833,
   "imagethumb": "e/ec/100_views_edo_106.jpg",
   "image": "e/ec/100_views_edo_106.jpg/120px-100_views_edo_106.jpg"
 },
 {
   "painting_index": 107,
   "title": "Fukagawa Susaki and Jūmantsubo (深川州崎十万坪, *Fukagawa Susaki Jūmantsubo*)",
   "depicted": "Mount Tsukuba",
   "remarks": "—",
   "date_of_painting": "1857-05",
   "latitude": 35.66611,
   "longitude": 139.809028,
   "imagethumb": "6/67/100_views_edo_107.jpg",
   "image": "6/67/100_views_edo_107.jpg/120px-100_views_edo_107.jpg"
 },
 {
   "painting_index": 108,
   "title": "View of Shiba Coast (芝うらの風景, *Shibaura no fūkei*)",
   "depicted": "Hamarikyu Gardens, *daiba*, Edo Bay",
   "remarks": "One of the first five prints sanctioned by the censors",
   "date_of_painting": "1856-02",
   "latitude": 35.65889,
   "longitude": 139.76861,
   "imagethumb": "6/68/100_views_edo_108.jpg",
   "image": "6/68/100_views_edo_108.jpg/120px-100_views_edo_108.jpg"
 },
 {
   "painting_index": 109,
   "title": "Minami Shinagawa and Samezu Coast (南品川鮫洲海岸, *Minamishinagawa Samezu kaigan*)",
   "depicted": "Edo Bay, Kaian-ji temple, Mount Tsukuba",
   "remarks": "Fishermen gather seaweed from submerged tree trunks",
   "date_of_painting": "1857-02",
   "latitude": 35.60639,
   "longitude": 139.74528,
   "imagethumb": "d/d0/100_views_edo_109.jpg",
   "image": "d/d0/100_views_edo_109.jpg/120px-100_views_edo_109.jpg"
 },
 {
   "painting_index": 110,
   "title": "\"Robe-Hanging Pine\" at Senzoku no ike (千束の池袈裟懸松, *Senzoku no ike Kesakakematsu*)",
   "depicted": "Senzoku no ike, \"Robe-Hanging Pine\", Hachiman Shrine",
   "remarks": "One of the first five prints sanctioned by the censors; Nichiren is said to have hung his monk's robe on this pine while resting",
   "date_of_painting": "1856-02",
   "latitude": 35.60125,
   "longitude": 139.69167,
   "imagethumb": "9/94/100_views_edo_110.jpg",
   "image": "9/94/100_views_edo_110.jpg/120px-100_views_edo_110.jpg"
 },
 {
   "painting_index": 111,
   "title": "Meguro Drum Bridge and Sunset Hill (目黒太鼓橋夕日の岡, *Meguro taikobashi Yūhi nooka*)",
   "depicted": "Drum Bridge, Meguro River",
   "remarks": "Publication date of this and three other prints (no. 24, 25, 84) depicting Meguro coincides with the exhibition of a Fudō Myōō icon",
   "date_of_painting": "1857-04",
   "latitude": 35.632278,
   "longitude": 139.71222,
   "imagethumb": "f/fc/100_views_edo_111.jpg",
   "image": "f/fc/100_views_edo_111.jpg/120px-100_views_edo_111.jpg"
 },
 {
   "painting_index": 112,
   "title": "Atagoshita and Yabu Lane (愛宕下薮小路, *Atagoshita Yabukōji*)",
   "depicted": "Yabu Lane, residences of the *daimyōs* Katō from Minakuchi and Hijikata from Komono, gate of Atago Shrine",
   "remarks": "Yabu Lane is to the far right beyond the bamboo thicket lining it",
   "date_of_painting": "1857-12",
   "latitude": 35.66806,
   "longitude": 139.750722,
   "imagethumb": "6/6c/100_views_edo_112.jpg",
   "image": "6/6c/100_views_edo_112.jpg/120px-100_views_edo_112.jpg"
 },
 {
   "painting_index": 113,
   "title": "Aoi Slope outside Toranomon gate (虎の門外あふひ坂, *Toranomon soto Aoizaka*)",
   "depicted": "Aoi Slope, moat",
   "remarks": "—",
   "date_of_painting": "1857-11",
   "latitude": 35.669611,
   "longitude": 139.747694,
   "imagethumb": "5/5e/100_views_edo_113.jpg",
   "image": "5/5e/100_views_edo_113.jpg/120px-100_views_edo_113.jpg"
 },
 {
   "painting_index": 114,
   "title": "Bikuni Bridge in Snow (びくにはし雪中, *Bikunihashi setchū*)",
   "depicted": "Bikuni Bridge, outer moat of Edo Castle",
   "remarks": "Believed to be created by Hiroshige II based on empty foreground, depiction of wall and schematic arrangement of snowflakes",
   "date_of_painting": "1858-10",
   "latitude": 35.675917,
   "longitude": 139.766444,
   "imagethumb": "7/72/100_views_edo_114.jpg",
   "image": "7/72/100_views_edo_114.jpg/120px-100_views_edo_114.jpg"
 },
 {
   "painting_index": 115,
   "title": "The Takata Riding Grounds (高田の馬場, *Takada no baba*)",
   "depicted": "Takata Riding Grounds",
   "remarks": "—",
   "date_of_painting": "1857-02",
   "latitude": 35.71,
   "longitude": 139.715,
   "imagethumb": "2/2f/100_views_edo_115.jpg",
   "image": "2/2f/100_views_edo_115.jpg/120px-100_views_edo_115.jpg"
 },
 {
   "painting_index": 116,
   "title": "Sugatami Bridge, Omokage Bridge and Jariba at Takata (高田姿見のはし俤の橋砂利場, *Takata Sugatami no hashi Omokage no hashi Jariba*)",
   "depicted": "Kanda River, Omokage Bridge, Hikawa rice field, Hikawa Shrine, Sugatami Bridge",
   "remarks": "Notable for striking colors; Tokugawa Iesada crossed the Omokage Bridge in the publication month",
   "date_of_painting": "1857-01",
   "latitude": 35.71325,
   "longitude": 139.71425,
   "imagethumb": "8/80/100_views_edo_116.jpg",
   "image": "8/80/100_views_edo_116.jpg/120px-100_views_edo_116.jpg"
 },
 {
   "painting_index": 117,
   "title": "View from the Hilltop of Yushima Tenjin Shrine (湯しま天神坂上眺望, *Yushima Tenjin sakaue chōbō*)",
   "depicted": "Yushima Tenjin Shrine, Shinobazu Pond, Kan'ei-ji",
   "remarks": "—",
   "date_of_painting": "1856-04",
   "latitude": 35.7075,
   "longitude": 139.768389,
   "imagethumb": "4/48/100_views_edo_117.jpg",
   "image": "4/48/100_views_edo_117.jpg/120px-100_views_edo_117.jpg"
 },
 {
   "painting_index": 118,
   "title": "Kitsunebi on New Year's Night under the Enoki Tree near Ōji (王子装束ゑの木大晦日の狐火, *Ōjishōzoku wenoki ōtsugomorihi no kitsunebi*)",
   "depicted": "Enoki tree",
   "remarks": "—",
   "date_of_painting": "1857-09",
   "latitude": 35.756417,
   "longitude": 139.737861,
   "imagethumb": "9/90/Hiroshige%2C_New_Year%27s_Eve_foxfires_at_the_changing_tree%2C_Oji%2C_1857.jpg",
   "image": "9/90/Hiroshige%2C_New_Year%27s_Eve_foxfires_at_the_changing_tree%2C_Oji%2C_1857.jpg/120px-Hiroshige%2C_New_Year%27s_Eve_foxfires_at_the_changing_tree%2C_Oji%2C_1857.jpg"
 },
 {
   "painting_index": 119,
   "title": "View of the Paulownia Imperiales Trees at Akasaka on a Rainy Evening (赤坂桐畑雨中夕けい, *Akasaka kiribatake uchū yūkei*)",
   "depicted": "Tameike Pond",
   "remarks": "Work by Hiroshige II; not always included in collections of One Hundred Famous Views of Edo; variously thought to be replacement print for no. 52, *The Paulownia Garden at Akasaka*, or a work on commission by Sakanaya Eikichi, celebrating Hiroshige II's adoption of his name and Hiroshige's seal",
   "date_of_painting": "1859-04",
   "latitude": 35.677611,
   "longitude": 139.73625,
   "imagethumb": "a/a8/Brooklyn_Museum_-_View_of_the_Kiribata_%28Paulownia_Imperiales%29_Trees_at_Akasaka_on_a_Rainy_Evening_-_Utagawa_Hiroshige_II.jpg",
   "image": "a/a8/Brooklyn_Museum_-_View_of_the_Kiribata_%28Paulownia_Imperiales%29_Trees_at_Akasaka_on_a_Rainy_Evening_-_Utagawa_Hiroshige_II.jpg/120px-Brooklyn_Museum_-_View_of_the_Kiribata_%28Paulownia_Imperiales%29_Trees_at_Akasaka_on_a_Rainy_Evening_-_Utagawa_Hiroshige_II.jpg"
 }
]